#!/bin/sh
mvn clean package && docker build -t saurabhsali/CustomerJWTService .
docker rm -f CustomerJWTService 2>/dev/null || true && docker run -it --name CustomerJWTService -p 8080:8080 -p 4848:4848 -p 8181:8181 --name CustomerJWTService saurabhsali/CustomerJWTService
